version: '3.8'

services:
  # ==========================================
  # SENSORES DE HARDWARE (Nós 1 a 8)
  # ==========================================
  sensor_1:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_1
    env_file: [ .env ]
    environment: [ NODE_ID=1 ]

  sensor_2:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_2
    env_file: [ .env ]
    environment: [ NODE_ID=2 ]

  sensor_3:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_3
    env_file: [ .env ]
    environment: [ NODE_ID=3 ]

  sensor_4:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_4
    env_file: [ .env ]
    environment: [ NODE_ID=4 ]

  sensor_5:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_5
    env_file: [ .env ]
    environment: [ NODE_ID=5 ]

  sensor_6:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_6
    env_file: [ .env ]
    environment: [ NODE_ID=6 ]

  sensor_7:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_7
    env_file: [ .env ]
    environment: [ NODE_ID=7 ]

  sensor_8:
    build: { context: ., dockerfile: docker/node.Dockerfile }
    container_name: sensor_8
    env_file: [ .env ]
    environment: [ NODE_ID=8 ]

  # ==========================================
  # ATUADORES FÍSICOS
  # ==========================================
  hvac_service:
    build:
      context: .
      dockerfile: docker/hvac.Dockerfile
    container_name: hvac_actuator
    env_file: [ .env ]
    ports:
      - "8081:8081" # ABERTO: Para o Servidor

  lb_service:
    build:
      context: .
      dockerfile: docker/lb.Dockerfile
    container_name: lb_actuator
    env_file: [ .env ]
    ports:
      - "8082:8082" # ABERTO: Para o Servidor

  # ==========================================
  # FRONT-END (Proxy Reverso)
  # ==========================================
  web_client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    container_name: web_client
    ports:
      - "80:80" 