version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: dc_backend
    restart: unless-stopped
    ports:
      - "9000:9000/udp" # Recebe dos sensores
      - "8080:8080/tcp" # Recebe do Nginx
    environment:
      # O Go já aponta nativamente para a Máquina B
      - HVAC_SERVICE_URL=http://${ACTUATORS_IP}:8081/trigger
      - LB_SERVICE_URL=http://${ACTUATORS_IP}:8082/trigger