version: '3.8'

x-sensor-base: &sensor-base
  build:
    context: .
    dockerfile: docker/node.Dockerfile
  networks:
    - dc_net

  depends_on:
    - central_server 

services:

  central_server:
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "9000:9000/udp"
    networks:
      - dc_net

  sensor_1:
    <<: *sensor-base
    environment:
      - NODE_ID=1
      - SERVER_ADDR=central_server:9000

  sensor_2:
    <<: *sensor-base
    environment:
      - NODE_ID=2
      - SERVER_ADDR=central_server:9000

  sensor_3:
    <<: *sensor-base
    environment:
      - NODE_ID=3
      - SERVER_ADDR=central_server:9000

  sensor_4:
    <<: *sensor-base
    environment:
      - NODE_ID=4
      - SERVER_ADDR=central_server:9000

networks:
  dc_net:
    driver: bridge